on: pull_request
name: CI Tests

jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["7.4", "8.0"]
        composer-args: ["--prefer-stable"]
        include:
          - php: "7.4"
            composer-args: "--prefer-lowest"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with specific version of PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: composer update ${{ matrix.composer-args }}
      - run: docker run -d --name wiremock -p 8080:8080 wiremock/wiremock
      - run: sleep 5
      - run: make test
      - run: docker rm -f wiremock
